version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 api:app
    container_name: paris_taxis_fares__api
    ports:
      - "5000:5000"

  client:
    build:
      context: client
      dockerfile: Dockerfile
    tty: true
    container_name: paris_taxis_fares__front
    command: yarn start
    ports:
      - "3000:3000"
    depends_on:
      - api